//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfParser.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchData
    {
        public int Id { get; set; }
        public int LeagueId { get; set; }
        public string MatchName { get; set; }
        public string TeamName { get; set; }
        public int TeamNo { get; set; }
    }
}
